### ISSUE TITLE
Texturing model

### ISSUE THREAD

**Issue by danperazzo** [ICT-VGL/ICT-FaceKit#11]
Hello, thanks for releasing this wonderful research! Just a question, is there any texturing model available for ICT? And, if so, do you plan on releasing it?

**Comment by saikiran321** [comment]
texture information is already available in the .obj files. You can write a parser to extract  vertex texture and face texture information

**Comment by danperazzo** [comment]
Ok that solves it, thank you :)

**Comment by Jia-Wei-Liu** [comment]
> Ok that solves it, thank you :)

Hi,
I have the same question. When I open the .obj file, I only see the vertex, not the vertex texture. Could you please tell me how did you manage to extract the vertex texture information? Thank you very much!

**Comment by sunjunlishi** [comment]
pleae give me a  face uv.jpg

**Comment by sunjunlishi** [comment]
![uv_face - 副本 (2)](https://github.com/ICT-VGL/ICT-FaceKit/assets/11845664/a2cafe98-d87b-4ebb-87a7-cdc95b05ff01)

**Comment by AlKhwarizmiCoder** [comment]
@sunjunlishi could you please tell me how have you generated this 2D image? I am new to this topic and need to transform the texture from multiple images onto a 3D model.
